Repository canonical/nginx-ingress-integrator-operator, pull requests merged in 2024-05, with the labels that each got.

#126 Fix missing ingress url in ingress relation
  requirements.txt
  src/charm.py
  src/ingress_definition.py
  tests/integration/test_ingress_relation.py
  tests/unit/test_ingress.py
  tests/unit/test_status.py
Labels: bug, Libraries: Out of sync

#129 Upgrade to v3 and get full cert chain
  lib/charms/nginx_ingress_integrator/v0/ingress.py
  lib/charms/tls_certificates_interface/v3/tls_certificates.py
  requirements.txt
  src/charm.py
  src/ingress_definition.py
  src/tls_relation.py
  tests/integration/provider_charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py
  tests/integration/provider_charm/src/charm.py
  tests/unit/test_cert_relation.py
Labels: Libraries: Out of sync, trivial

#135 Make NginxRouteRequirer public
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
Labels: Libraries: Out of sync, trivial

#136 Rename get_additional_hostnames to reflect what it does
  src/charm.py
Labels: Libraries: Out of sync, trivial

#143 Add check for remote units before considering ingress relation ready
  .github/workflows/test.yaml
  src/charm.py
Labels: bug, Libraries: Out of sync, trivial

#142 use dict.get() to fetch cert
  src/charm.py
Labels: Libraries: Out of sync, trivial
